###############
#   GENERAL   #
###############

baseURL: https://lost-scripts.github.io/
languageCode: en-us
title: Lost Scripts™
copyright: Copyright © 2025 · Rai López · All Rights Reserved
timezone: Europe/Madrid
theme: lost-theme
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholder: true
publishDir: docs # Use `hugo server --destination public` (or alias `hs` if configured) for previewing and `hugo --destination docs` (or `h`) for final generation.
relativeURLs: true
uglyURLs: false


###############
# PERFORMANCE #
###############

cleanDestinationDir: true # remove files from destination not found in static directories
disableFastRender: true # Enables full re-renders on changes (commented cause this setting doesn't really belong here...)
#disableKinds: ['taxonomy', 'taxonomyTerm', 'term', ' robotsTXT', 'RSS', 'sitemap', '404'] # Reduce rendering complexity if you don't need taxonomies

services:
  rss:
    limit: 10


###############
#   CONTENT   #
###############

# Navigation tabs
menus:
  nav:
    - name: Scripts
      pre: fa-file-code #'/icons/fa-file-code-solid.svg' #'📄'
      title: Scripts
      identifier: scripts
      url: /scripts/
      weight: 1
      params:
        item: Script
        #readmes: true

    - name: Docs
      pre: fa-book #'/icons/fa-book-solid.svg' #'📚'
      title: Documentation
      identifier: docs
      url: /docs/
      weight: 2
      params:
        item: Document
        #comments: false

    - name: Lab
      pre: fa-flask #'/icons/fa-flask-solid.svg' #'🧪'
      title: Lab!
      identifier: lab
      url: /lab/
      weight: 3
      params:
        item: Experiment

    - name: Blog
      pre: fa-blog #'/icons/fa-blog-solid.svg' #'🅱'
      title: Blog
      identifier: posts
      url: /posts/
      weight: 4
      params:
        item: Post
        hidden: true

languages:
  en:
    title: Here be Lost Scripts
    languageCode: en
    languageName: English
    weight: 1
  es:
    title: Aquí hay Lost Scripts
    languageCode: es
    languageName: Español
    weight: 2
  ca:
    title: Aquí hi ha Lost Scripts
    languageCode: ca
    languageName: Català
    weight: 3

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true # Allow HTML in md files (WARNING: make sure content is under your control!)
    renderHooks:
      image:
        enableDefault: true # 20250629-1130: Changed to false cause it messed MD relative image paths!  
    parser:
      autoIDType: github
      autoHeadingID: true
      wrapStandAloneImageWithinParagraph: false
      attribute:
        title: true
        block: true
  highlight:
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    style: monokai
    #noClasses: false
    #hl_Lines: '1 4-6'

mediaTypes:
  application/x-readme:
    suffixes: ["html"] # Aunque sea un archivo HTML, le damos un tipo MIME único para Hugo

outputs:
  home:
    - html
    - json
    - rss
  page:
    - html
    - README

outputFormats:
  README:
    mediaType: "application/x-readme"
    baseName: "README"
    is: true
    isPlainText: false
    noUgly: true


###############
#    OTHER    #
###############

params:
  homepage: /scripts/ls/
  homeIcon: house
  subtitle: The Lost (Moho® Scripts) Ark
  author:
    name: Rai López
    homepage: https://lost-scripts.github.io/
  copyrightAlt: © 2025 · Rai López · <abbr title="All Rights Reserved">ARR</abbr>
  since: 2024
  navMode: auto # auto (default) / tabbed / accordion
  readmes: true
  comments: true
  giscus:
    repo: lost-scripts/lost-scripts.github.io
    repoId: R_kgDOONd4Hw
    categoryId: DIC_kwDOONd4H84CpGLA
    themeLight: catppuccin_latte
    themeDark: catppuccin_frappe
  aside: false
  banner: false
  ribbon: true
  hugo: true
  faStyle: solid
  swatchLight:
    - "#98403A"
    - "#8A7F05"
    - "#088C34"
    - "#3F67A6"
    - "#9F1D7D"
  swatchDark:
    - "#F75447"
    - "#E8CF28"
    - "#8FD938"
    - "#40BAEB"
    - "#BE6DDF"
  headingIconSize: 1 # Size multiplier (default: 40px)
  headingIconTint: true
  #debug: true

  # Social Networking and Contact Links (use e.g. `order: 1`, etc. for override ordering)
  links:
    - href: https://github.com/lost-scripts
      icon: fa-brands fa-github
      alt: GitHub
      title: GitHub...
    - href: mailto:rai.lopez@outlook.com
      icon: fa-solid fa-envelope
      alt: Email
      title: Email...
    - href: /index.xml
      icon: fa-solid fa-rss
      alt: Subscribe?
      title: Subscribe?
      rel: alternate
      type: application/rss+xml
    - href: https://instagram.com/Lost_Scripts
      icon: fa-brands fa-instagram
      alt: Instagram
      title: Instagram...
    - href: https://mohoscripting.com/
      src: /icons/icon_ms_logo.svg
      alt: Moho Scripting
      start: "Other Links:"
      title: Moho Scripting...
    - href: /about
      icon: fa-solid fa-circle-info
      alt: About
      title: About

  # Other Links...
  linksAlt:
    hosting: https://pages.github.com/
    hostingStatus: https://www.githubstatus.com/